/**
 * @description       : 
 * @author            : Subramani Kumarasamy
 * @group             : 
 * @last modified on  : 07-11-2023
 * @last modified by  : Subramani Kumarasamy
**/
public class AirlinesWrapper {
    
    public Integer id;
    public String name;
    public String country;
    public String logo;
    public String slogan;
    public String head_quaters;
    public String website;
    public String established; 
}